name: GuerrillaPlugin
guerrillaPlugin: net.spikedboy.guerrilla.GuerrillaPlugin
commands:
   gc:
      description: Toggles guerrilla chat
      usage: /gc
      permission:
   g:
     description: 
     usage: type /g help [page] for more info
     permission:      
   guerrillaPlugin:
     description: 
     usage: type /guerrilla help [page] for more info
     permission: 
   gmakemap:
     description:
     usage:
     permission: